version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - products-app

  products-web-app:
    image: products-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - products-app

volumes:
  db:
    driver: local

networks:
  products-app: